### ISSUE TITLE
datetime with timezone can't be parsed

### ISSUE THREAD

**Issue by Remo** [mlocati/MediaData#1]
This call fails for me https://github.com/mlocati/MediaData/blob/master/Processor/ImageProcessor/ExivImageProcessor.cs#L86

The value of `chunks[1]` is `2009-03-19T15:02:36+01:00` in my case.

File was saved with Adobe Photoshop CS4 Macintosh.

**Comment by mlocati** [comment]
@Remo Could you send me an email with a photo with exif data like `2009-03-19T15:02:36+01:00`?
I'd like to check how MediaData handles timezones in that case...

**Comment by Remo** [comment]
you've got mail

**Comment by mlocati** [comment]
Thanks! I [fixed the handling of time zones in exif metadata](https://github.com/mlocati/MediaData/blob/1f757eeb83b2e484fb43d22f0643ac6096c3bee3/Processor/ImageProcessor/ExivImageProcessor.cs#L92-L95).
